### ISSUE TITLE
Multiple cuts saved to a single file

### ISSUE THREAD

**Issue by DaSandman** [bartekmotyl/simple-video-cutter#93] opened 2024-04-15 04:00 UTC
Was the ability to perform multiple cuts on a video and save the output to a single file ever implemented in SVC?  I saw requests, and your supportive replies dating back as far as 2020, but based on SVC's description, it's not clear to me that it's capable of this.

**Comment by bartekmotyl** [comment] 2024-04-16 18:59
There is already a request opened for this feature - #51, thus marking this one as a duplicate. 

In general, this sounds as a nice idea, but from implementation point of view it is not that easy. On the other hand, it can be easily achieved with some post-processing (e.g. a simple script that uses `ffmpeg`)

**Comment by bartekmotyl** [comment] 2024-04-16 18:59
Closing as duplicate of #51

**Closed as not planned by bartekmotyl** 2024-04-16 18:59 UTC
Labels: duplicate
