### ISSUE TITLE
Volume at 0 when opening

### ISSUE THREAD

**Issue by CBRPLX** [bartekmotyl/simple-video-cutter#94] opened 2024-05-10 13:50 UTC
Hi, everytime I open it, the volume is at 0. I have to manually put it to 100.
Do you know how to make the volume level persistent ? 

![ApplicationFrameHost_wkyTZ2K64f](https://github.com/bartekmotyl/simple-video-cutter/assets/10628388/94fb710c-b14a-4787-afcd-840cd6992843)

**Comment by bartekmotyl** [comment] 2024-05-10 20:47
Indeed, I can reproduce the issue as well on my machine. I am pretty sure it worked fine previously, maybe the problem was introduced after recent vlc library upgrade.

**Comment by bartekmotyl** [comment] 2024-05-10 20:51
I fixed it in development branch (commit f5cc7e2ed4e1c72e85c55afca7485fe6bb17a5e3 but I made a mistake in the commit message referencing the wrong ticket). Fix will be included in next release.

**Closed as completed by bartekmotyl** 2024-05-10 20:51 UTC
Labels: bug

**Comment by bartekmotyl** [comment] 2024-05-10 20:57
Unfortunately there is no workaround for the version 0.30 unless the fixed version is released.

**Comment by CBRPLX** [comment] 2024-05-10 21:10
Ok no prob, thank you for fixing it 👏 
Do you have any idea when the next release will be ?

**Comment by bartekmotyl** [comment] 2024-05-10 21:21
Is already in progress, should be available within 1 or 2 hours  :)

**Comment by bartekmotyl** [comment] 2024-05-10 21:32
Note: after the fix, volume level set in the mixer should be persisted. 
If due to earlier bug it is still zero, please adjust manually - next time you start Simple Video Cutter it should be ok.

**Comment by CBRPLX** [comment] 2024-05-12 20:10
I confirmed it is fixed now. Thank you @bartekmotyl
