### ISSUE TITLE
Output video doesn't match selected time

### ISSUE THREAD

**Issue by uhlstefa** [bartekmotyl/simple-video-cutter#68] opened 2022-10-19 16:38 UTC
I have edited an AVI Video multiple times, but noticed that every output video starts about 3 sec before the start time I selected.
Is this an issue or do I need to do some configuration?

Pls support.

**Comment by bartekmotyl** [comment] 2022-10-19 19:34
Can you provide a screenshot of your timeline (including selection)? 
Do you perform lossless cut (on keyframes) or cut with re-encoding?

**Comment by uhlstefa** [comment] 2022-10-20 20:11
I did with lossless cut. Sometimes, the videos are as I selected start and end, sometimes more seconds are added.
Happens both lossless and recode optin.

**Comment by uhlstefa** [comment] 2022-10-20 20:16
![Screenshot 2022-10-20 221607](https://user-images.githubusercontent.com/104195810/197049258-b815ae3a-bb6f-4765-a454-ceb7ce6dae12.jpg)

**Comment by bartekmotyl** [comment] 2022-10-31 21:45
Hmm, according to your screenshot, there are no keyframes in your file thus lossless cut is rather not possible 🤔 
Can you try to cut-with-reencoding ? (press `shift` when clicking on `perform cut`).
Can you try with a sample file that can be found here https://download.blender.org/demo/movies/BBB/ ?

**Comment by bartekmotyl** [comment] 2023-02-24 20:09
Closing, as cannot reproduce. Please reopen in case you can provide more details or reproduction procedure.

**Closed as not planned** 2023-02-24 20:09 UTC
Labels: bug
