### ISSUE TITLE
[Feature request] backward frame button & keystroke

### ISSUE THREAD

**Issue by the-liquid-metal** [bartekmotyl/simple-video-cutter#42] opened 2021-11-30 21:35 UTC
There is forward button, but no backward button. If we want to seek prev frame, we have to click the timelime. This is very annoying for lenghty movies. the current frame is too far from the target frame. Moreover, there is no jump button (forward and backward). it would be better if jump buttons is configurable: every definitive seconds/minutes and changeable keystroke.

**Comment by bartekmotyl** [comment] 2021-11-30 21:43
This is duplicate of issue #15. The reason for lack of this function is the fact is it not provided by the library (libvlc) that is used to play the video. 
Note: positioning depends on file type. For example, in case of mp4 you can position only in certain places/frames (depends on video file properties)

**Closed as completed by bartekmotyl** 2021-11-30 21:43 UTC
Labels: duplicate

**Comment by the-liquid-metal** [comment] 2021-11-30 22:01
Is there any chance for jump button?
VLC has jump button. Moreover, it has 4 type of jump: very short, short, medium, and long. All are forward and backward. Although its just hotkeys.
