### ISSUE TITLE
why is wmv output can not be played on media player classic?

### ISSUE THREAD

**Issue by the-liquid-metal** [bartekmotyl/simple-video-cutter#46] opened 2021-11-30 23:19 UTC
wmv output can not be played on media player classic, but can be played on vlc.

**Comment by bartekmotyl** [comment] 2021-12-01 20:33
Can source be played on media player classic?
In general, Simple Video Cutter uses ffmpeg to perform conversion, so if something is wrong with the output file, then it is probably caused by ffmpeg. But I rather think the opposite - media player classic may not support this format (codec?) 

Just to note: one can try to create a custom profile in order to pass custom options to ffmpeg.

**Comment by the-liquid-metal** [comment] 2021-12-01 21:35
> Can source be played on media player classic?

Yes, MPC can play it.

> media player classic may not support this format (codec?)

If ffmpeg do lossless, than the codec should be the same.

**Comment by bartekmotyl** [comment] 2021-12-03 14:55
Do you maybe have a n example of such file? Maybe one of videos found on https://filesamples.com/categories/video ?

**Comment by bartekmotyl** [comment] 2022-02-12 10:51
Closing as not possible to reproduce.

**Closed as completed by bartekmotyl** 2022-02-12 10:51 UTC
